Repository milharal-dev/detona-dev, pull requests merged in 2024-08, with the labels that each got.

#1 refactor: file structure since we'll have two services in one repo
  README.md
  frontend/.eslintrc.cjs
  frontend/.prettierignore
  frontend/.prettierrc
  frontend/index.html
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/index.css
  frontend/src/layouts/components/footer/footer.tsx
  frontend/src/layouts/components/navbar/navbar.tsx
  frontend/src/layouts/main/main-layout.tsx
  frontend/src/layouts/main/main-layout.types.ts
  frontend/src/main.tsx
  frontend/src/pages/home/home.tsx
  frontend/src/providers/providers.tsx
  frontend/src/providers/providers.types.ts
  frontend/src/routes/AppRouter.tsx
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  src/infrastructure/services/index.ts
Labels: enhancement

#2 refactor: readme update
  README.md
Labels: enhancement

#13 chore: Adding code owners configuration
  .github/CODEOWNERS
Labels: chore

#12 feat: frontend v1
  frontend/.eslintrc.cjs
  frontend/components.json
  frontend/index.html
  frontend/package.json
  frontend/src/components/interactive/button/button.tsx
  frontend/src/components/interactive/button/button.types.ts
  frontend/src/components/interactive/input/index.tsx
  frontend/src/components/interactive/input/input.types.ts
  frontend/src/components/interactive/textarea/index.tsx
  frontend/src/components/interactive/textarea/textarea.types.ts
  frontend/src/hooks/useForm/index.tsx
  frontend/src/hooks/useForm/useForm.types.ts
  frontend/src/index.css
  frontend/src/layouts/components/footer/footer.tsx
  frontend/src/layouts/components/footer/index.tsx
  frontend/src/layouts/components/header/index.tsx
  frontend/src/layouts/components/navbar/navbar.tsx
  frontend/src/layouts/main/main-layout.tsx
  frontend/src/libs/utils.ts
  frontend/src/main.tsx
  frontend/src/pages/home/components/form/index.tsx
  frontend/src/pages/home/components/loading/index.tsx
  frontend/src/pages/home/components/result/index.tsx
  frontend/src/pages/home/home.tsx
  frontend/src/pages/home/index.tsx
  frontend/src/providers/index.tsx
  frontend/src/routes/AppRouter.tsx
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/vite.config.ts
Labels: enhancement, frontend

#14 feat: backend-init
  backend/.env.example
  backend/package.json
  backend/src/index.ts
  backend/src/libs/octokit.ts
  backend/src/libs/openai.ts
  backend/src/libs/twit.ts
  backend/tsconfig.json
Labels: enhancement, backend
